### ISSUE TITLE
Phone number suggestion not working on Android 12 devices

### ISSUE THREAD

**Issue by cscipher** [Tkko/flutter_smart_auth#6]
When we request hints for phone number suggestions, the dialog loads for less than a second and then disappears on android 12 devices. I tried with other android versions and it was working fine there.

**Comment by fidelisakilan** [comment]
+1 Facing similar issue on 3 devices i have tested so far.
Samsung m 13 Android 12
Realme 3 pro Android 12
Mi A3 Android 11

**Comment by danishkhawaja98** [comment]
Hi @fidelisakilan , @cscipher!

This is not due to the package, android versions or mobile devices. Actually, it's a network carrier issue.
You can identify this by going to settings > About Phone > Basic info **_(Phone number)_** and assure that you are not getting **"Unknown Number"** in the field. If you are getting **"Unknown Number"** then the package would return _null_, and the dialog will disappear.
Here is the image:
![s2mxgumlic051](https://user-images.githubusercontent.com/114078857/218739676-f40217a1-be5d-46e0-b579-05d7873a95bc.png)

`Possible Solutions:`

1.  Eject your sim from android device and insert it into iPhone. Wait for few seconds for the sim info to get read by iPhone. Eject from iPhone and insert again in your android device. Hopefully, now you will be getting **"<your-number>"** instead of **"Unknown Number."**

2.  Some devices like _HUAWEI_, _OPPO_ etc. has the ability to edit your sim numbers for "**_Phone Number Hint_**". You can do this by going to Network & internet > SIM card manager > Click on the pen **_(or any edit icon)_** > You can edit your number and save it.

3.  Go to your Network Carrier Office.
